# Generated by Django 5.2.5 on 2026-01-03 08:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
